#!/bin/bash

#get profile
profile=$(gsettings get org.gnome.Terminal.ProfilesList default)
profile=${profile:1:-1} # remove leading and trailing single quotes

#set wallpaper
gsettings set org.gnome.desktop.background picture-uri file:///home/fedzilla/Pictures/screenbot/wallpapers/wallhaven-626507_1920x1080.png

#set theme and icons
gsettings set org.gnome.desktop.interface icon-theme HighContrast
gsettings set org.gnome.desktop.interface gtk-theme Numix

#set transparency rules         
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile}/ use-transparent-background true 
gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile}/ background-transparency-percent "10"                            

#set foreground and background  
#gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile}/ background-color "#0c0c0c"
#gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile}/ foreground-color "#c4c4db"
#caf7ce

#turn on/off theme colors 
gsettings set  org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile}/ use-theme-colors true

