#!/bin/bash

#### Documentation
# Gogh Themes 
# Color Scheme for Gnome Terminal Terminal 
# https://github.com/Mayccoll/Gogh



#### Utiliities
URL="https://git.io/"
sudo mkdir "/tmp/Gogh_Themes/"
TMPDIR="/tmp/Gogh_Themes/"

function gogh_theme() [THEME] [EXT]
{
	local THEME=$1
	local EXT=$2
	wget -O ${TMPDIR}${name}  "${URL}${EXT}." 
}

#### Gogh Theme List
gogh_theme xxxx xxxx


#### Install Themes 
sudo chmod +x ${TMPDIR}* && .${TMPDIR}* && rm -rf ${TMPDIR}

####code to keep
# Declare -A PROFILES
# PROFILES=( ["$THEME"]="${EXT}" \


#### CODE TO KEEP
# for THEME in PROFILES; do
#	wget -O /tmp/Gogh/${THEME}
#	${THEME}_PROFILE=$(dconf dump /org/gnome/terminal/legacy/profiles:/ | grep -B 2 "Dracula" | sed -n 1p)            
#	${THEME}_PROFILE=${PROFILE:2:-1} 	

