#!/bin/bash

#### DOCUMENTATION
#documentatin goes here

####utilities

function SET_SCREEN()
{
	# set wallpaper
	echo "wallpaper"
	gsettings set org.gnome.desktop.background picture-uri file:///home/Pictures/screenbot/wallpapers/${wallpaper}

	#  set gtk-theme, shell-theme,  and icons
	#gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
	gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
	#gsettings set org.gnome.shell.extensions.user-theme name $SHELL_THEME

	# get profile
        profile=$(gsettings get org.gnome.Terminal.ProfilesList default)
        profile=${profile:1:-1} # removes quotes

	# set $PS1 color
	# #export $PS1=$\PS1

	# set shell theme colors on/off, transparency, foreground, and background
	gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile}/ use-theme-colors $THEME_COLORS_T_F         
	gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile}/ use-transparent-background $SHELL_TRANSPARENT_T_F 
	#gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile}/ background-transparency-percent $SHELL_TRANSPARENCY_PERCENTAGE                            
	gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile}/ background-color \"$BG_COLOR\"
	gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${profile}/ foreground-color \"$FG_COLOR\"
}

function RANDOM_SCREEN()
{
        SCREEN_LIST=("screen-1" "screen-2" "screen-3")
        SIZE=${#SCREEN_LIST[@]}
        index=$(($RANDOM % $SIZE))                                                                                                   
        SCREEN=${SCREEN_LIST[$index]}
}   

	
function SCREEN_PARAMETERS()
{
	case $SCREEN in
#		screen-1|Forrest)
#                        echo "Forrest (screen-1)"
#                        WALLPAPER="Forrest-(wallhaven-582230)1920x1080.png"
#                        ICON_THEME="Numix-Circle"
#                        GTK_THEME="Adapta-Nokto"
#                        SHELL_THEME="EvoPop"
#			 THEME_COLORS_T_F="false"
#                        SHELL_TRANSPARENT_T_F="true"
#                        SHELL_TRANSPERENCY_PERCENTAGE='10'
#                        BG_COLOR="#242C2E"
#                        FG_COLOR="D5BEAB"
#                        #PS1_COLOR="#24AFBB"
#                ;;
#                screen-2|Dusk_Mountains_Flat)
#                        echo "Dusk_Mountains_Flat (screen-2)" 
#                        WALLPAPER="679478.jpg "
#                        ICON_THEME="Numix-Circle"
#			3GTK_THEME="Numix"
#                        SHELL_THEME="Arc-Red-Dark"
#                        THEME_COLORS_T_F="false"
#                        SHELL_TRANSPARENT_T_F="true"
#                        SHELL_TRANSPERENCY_PERCENTAGE="25"
#                        BG_COLOR="#FFDCC8"
#                        FG_COLOR="#2D112A"
#                        #PS1_COLOR="#????"
#                ;;
#                screen-3|Saw_Mill_Flat)
#                        echo "Saw_Mill_Flat (screen-3)"
#                        WALLPAPER="clement-dartigues-scirie.jpg "
#                        ICON_THEME="Numix-Circle"
#                        GTK_THEME="EvoPop-Azure"
#                        SHELL_THEME="EvoPop"
#                        THEME_COLORS_T_F="false"
#                        SHELL_TRANSPARENT_T_F="false"
#                        SHELL_TRANSPERENCY_PERCENTAGE="0"
#                        BG_COLOR="#206064" #"#183F47"
#                        FG_COLOR="#F3F3F3"
                        #PS1_COLOR="#????"
#                ;;
##                screen-4|Lonely_Cosmic_Fantasy)
#                        echo "Lonely_Cosomic_Fantasy (screen-4 )"
#                        WALLPAPER="clement-dartigues-scirie.jpg "
#                        ICON_THEME="Paper" #"Numix-Circle"
#                        GTK_THEME="Vertex-Dark"
#                        SHELL_THEME="Adapta-Eta"
#                        THEME_COLORS_T_F="false"
#                        SHELL_TRANSPARENT_T_F="true"
#                        SHELL_TRANSPERENCY_PERCENTAGE="30"
#                        BG_COLOR="#000000" #"#183F47"
#                        FG_COLOR="27D9F1" #or "#F3F3F3" and PS1
#                        #PS1_COLOR="#????" #26F1A3
#		;;	
         #    screen-1|Forrest)
#                        echo "Forrest (screen-1)"
#                        WALLPAPER="Forrest-(wallhaven-582230)1920x1080.png"
#                        ICON_THEME="Numix-Circle"
#                        GTK_THEME="Adapta-Nokto"
#                        SHELL_THEME="EvoPop"
#                        THEME_COLORS_T_F="false"
#                        SHELL_TRANSPARENT_T_F="true"
#                        SHELL_TRANSPERENCY_PERCENTAGE='10'
#                        BG_COLOR="#242C2E"
#                        FG_COLOR="D5BEAB"
#                        #PS1_COLOR="#24AFBB"

		screen-1|Forrest)
		echo "Forrest (screen-1)"
			wallpaper="Forrest-wallhaven-582230-1920x1080.png"
			echo "$wallpaper"
			ICON_THEME="Numix-Circle"
			GTK_THEME="Adapta-Nokto"
			SHELL_THEME="EvoPop-Azure"
			THEME_COLORS_T_F="false"
			SHELL_TRANSPARENT_T_F="true"
			SHELL_TRANSPERENCY_PERCENTAGE="10"
			BG_COLOR="#242C2E"
			FG_COLOR="#24AFBB"
		;;
		#screen-2)
			###WALLPAPER
			#ICON_THEME="Paper"
			#GTK_THEME="EvoPop-Azure"
			###SHELL_THEME
			#THEME_COLORS_T_F="false"
			#SHELL_TRANSPARENT_T_F="true"
			#SHELL_TRANSPERENCY_PERCENTAGE="10"
			#BG_COLOR="#1e1d30"
			#FG_COLOR"#ccf5d7"
		#;;
		#screen-3)
			###WALLPAPER
			#ICON_THEME="Paper"
			#GTK_THEME="Paper"
			#SHELL_THEME="Paper"
			#THEME_COLORS_T_F="false"
			#SHELL_TRANSPARENT_T_F="true"
			#SHELL_TRANSPERENCY_PERCENTAGE="10"
			#BG_COLOR="#0f5062"
			#FG_COLOR="#efd097"
		#;;
		*)
			printf "\nSorry that is not a legitamate screen.\nUse the command 'screenbot' without arguements for help"
			exit
	esac	
}

####command options

case $1 in
	--random|-r)
		RANDOM_SCREEN
		SCREEN_PARAMETERS
		SET_SCREEN		
	;;
	--list|-l)
		printf "\n#SCREEN-LIST HERE\n"
	;;
	"")
		printf "\nHELP-GOES-HERE\n"
	;;
	*)
		SCREEN="${1#*=}"
		echo "SCREEN:$SCREEN"
		SCREEN_PARAMETERS
		SET_SCREEN
esac

echo "@:$@ 1:$1"


#### template for adding additional screens
#screen-x
#WALLPAPER
#ICON_THEME
#GTK_THEME
#SHELL_THEME
#THEME_COLORS_T/F
#SHELL_TRANSPARENT_T/F
#SHELL_TRANSPERENCY_PERCENTAGE
#BG_COLOR
#FG_COLOR

