#!/bin/bash

#### DOCUMENTATION
#documentatin goes here

####utilities

function SET_SCREEN()
{
	# set wallpaper
	gsettings set org.gnome.desktop.background picture-uri file:///home/Pictures/screenbot/wallpapers/${wallpaper}

	# set gtk-theme, shell-theme,  and icons
	gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
	gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
	gsettings set org.gnome.shell.extensions.user-theme name $SHELL_THEME

	# get profile
	PROFILE=$(dconf dump /org/gnome/terminal/legacy/profiles:/ | grep -B 2 ${GOGH_THEME} | sed -n 1p)                        
	PROFILE=${PROFILE:2:-1}                                                                                         
	gsettings set org.gnome.Terminal.ProfilesList default $PROFILE 
        # profile=$(gsettings get org.gnome.Terminal.ProfilesList default)
        # profile=${profile:1:-1} # removes quotes

	# set $PS1 color
	# #export $PS1=$\PS1

	# set shell theme colors on/off, transparency, foreground, and background
	gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${PROFILE}/ use-theme-colors $THEME_COLORS_T_F         
	gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${PROFILE}/ use-transparent-background $SHELL_TRANSPARENT_T_F 
	gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${PROFILE}/ background-transparency-percent $SHELL_TRANSPARENCY_PERCENTAGE                         
	gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${PROFILE}/ background-color \"$BG_COLOR\"
	gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:${PROFILE}/ foreground-color \"$FG_COLOR\"
}

function RANDOM_SCREEN()
{
        SCREEN_LIST=("screen-1" "screen-2" "screen-3")
        SIZE=${#SCREEN_LIST[@]}
        index=$(($RANDOM % $SIZE))                                                                                                   
        SCREEN=${SCREEN_LIST[$index]}
}   

function SCREEN_PARAMETERS()
{
	case $SCREEN in
		screen-1|Forrest)
			echo "Forrest (screen-1)"
			wallpaper="Forrest-wallhaven-582230-1920x1080.png"
			echo "wallpaper:$wallpaper"
			ICON_THEME="Numix-Circle"
			GTK_THEME="Adapta-Nokto"
			SHELL_THEME="EvoPop-Azure"
	#		GOGH_THEME="Dracula"
			THEME_COLORS_T_F="false"
			SHELL_TRANSPARENT_T_F="true"
			SHELL_TRANSPARENCY_PERCENTAGE="10"
			# BG_COLOR="#283337" #"#182B2E" #"#38423E" #"#C0B7AF" #"#242C2E"
			# FG_COLOR="#C0B7AF" #"#38423E" #":D5BAEB"
		;;
		screen-2|Forrest-Light)
			echo "Forrest (screen-1)"
			wallpaper="Forrest-wallhaven-582230-1920x1080.png"
			echo "wallpaper:$wallpaper"
			ICON_THEME="Numix-Circle"
			GTK_THEME="Adapta-Eta"
			SHELL_THEME="EvoPop-Azure"
			###GOGH_THEME="xxxx"
			THEME_COLORS_T_F="false"
			SHELL_TRANSPARENT_T_F="true"
			SHELL_TRANSPARENCY_PERCENTAGE="20"
			BG_COLOR="#182B2E" #"#38423E" #"#C0B7AF" #"#242C2E"
			FG_COLOR="#C0B7AF" #"#38423E" #":D5BAEB"
		;;
		screen-3|Saw_Mill-Flat)
			echo "Saw_Mill-Flat (screen-3)"
			wallpaper="clement-dartigues-scirie.jpg"
			ICON_THEME="Paper"
			GTK_THEME="EvoPop-Azure"
			SHELL_THEME="EvoPop-Azure"
			THEME_COLORS_T_F="false"
			SHELL_TRANSPARENT_T_F="false"
			SHELL_TRANSPARENCY_PERCENTAGE="0"
			BG_COLOR="#206064" #"#183F47"
			FG_COLOR="#F3F3F3"
			#PS1_COLOR="#????"
		;;
		screen-4|Dusk_Mountains-Flat)
			echo "Dusk_Mountain-Flat (screen-4)"
			wallpaper="679478.jpg"
			ICON_THEME="Numix-Circle"
			GTK_THEME="Numix"
			SHELL_THEME="Arc-Red-Dark"
			GOGH_THEME="Chalk"
			THEME_COLORS_T_F="false"
			SHELL_TRANSPARENT_T_F="true"
			SHELL_TRANSPARENCY_PERCENTAGE="25"
			# BG_COLOR="#FFDCC8"
			# FG_COLOR="#2D112A"
			#PS1_COLOR="#????"
		;;
 		screen-5|Cosmic_Fantasy)
			echo "Cosmic_Fantasy (screen-5)"
			wallpaper="wallhaven-592459_1920x1080.png"
			ICON_THEME="Paper" #"Numix-Circle"
			GTK_THEME="Arc-Red-Dark"
			SHELL_THEME="Adapta-Eta"
			THEME_COLORS_T_F="false"
			SHELL_TRANSPARENT_T_F="true"
			SHELL_TRANSPARENCY_PERCENTAGE="50"
			BG_COLOR="#1A1311A" #"#000000" #"#183F47"
		        FG_COLOR="#27D9F1" #or "#F3F3F3" and PS1
                        #PS1_COLOR="#????" #26F1A3	
		;;
		screen-6|I_AM_ROOT)
			echo "I_AM_ROOT (screen-6)"
			wallpaper="wallhaven-494982_1920x1080.png"
			ICON_THEME="Paper"
			GTK_THEME="Arc-Flatabulous-Dark"
			SHELL_THEME="Arc-Flatabulous-Dark"
			THEME_COLORS_T_F="false"
			SHELL_TRANSPARENT_T_F="true"
			SHELL_TRANSPARENCY_PERCENTAGE="15"
			BG_COLOR="#FFDCC8"
			FG_COLOR="#2D112A"
			#PS1_COLOR="#????"
		;;
		*)
			printf "\nSorry that is not a legitamate screen.\nUse the command 'screenbot' without arguements for help"
			exit
	esac	
}

####command options


case $1 in
	--random|-r)
		RANDOM_SCREEN
		SCREEN_PARAMETERS
		SET_SCREEN		
	;;
	--list|-l)
		printf "\n#SCREEN-LIST HERE\n"
	;;
	"")
		printf "\nHELP-GOES-HERE\n"
	;;
	*)
		SCREEN="${1#*=}"
		SCREEN_PARAMETERS
		SET_SCREEN
esac
printf

